/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BIOSKOP;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Naufal Wilanjana
 */
public class BioskopQ extends javax.swing.JFrame {

    /**
     * Creates new form BioskopQ
     */
    public BioskopQ() {
        initComponents();
        kursihilang(); //membuka method kursi hilang
    }
    
    int harga; //harga jenis teater
    //method untuk membuat inputan hanya angka
    public void FilterAngka(KeyEvent b) {
        if (Character.isAlphabetic(b.getKeyChar())) {
            b.consume();
            //Pesan Dialog Boleh Di Hapus Ini Hanya Sebagai Contoh
            JOptionPane.showMessageDialog(null, "Masukan Hanya Angka", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }
    //akhir dari method inputan hanya angka
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RBGWaktuFilm = new javax.swing.ButtonGroup();
        RBGJenisTeater = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbNamaFilm = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        RB1 = new javax.swing.JRadioButton();
        RB2 = new javax.swing.JRadioButton();
        RB3 = new javax.swing.JRadioButton();
        RB4 = new javax.swing.JRadioButton();
        RB5 = new javax.swing.JRadioButton();
        RB6 = new javax.swing.JRadioButton();
        RB7 = new javax.swing.JRadioButton();
        RB8 = new javax.swing.JRadioButton();
        RB9 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        RBReguler = new javax.swing.JRadioButton();
        RBPlatinum = new javax.swing.JRadioButton();
        RBGold = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        txtJumlahTiket = new javax.swing.JTextField();
        btnPilihKursi = new javax.swing.JButton();
        CBa1 = new javax.swing.JCheckBox();
        CBa2 = new javax.swing.JCheckBox();
        CBa3 = new javax.swing.JCheckBox();
        CBa4 = new javax.swing.JCheckBox();
        CBa5 = new javax.swing.JCheckBox();
        CBb1 = new javax.swing.JCheckBox();
        CBb2 = new javax.swing.JCheckBox();
        CBb3 = new javax.swing.JCheckBox();
        CBb4 = new javax.swing.JCheckBox();
        CBb5 = new javax.swing.JCheckBox();
        CBc1 = new javax.swing.JCheckBox();
        CBc2 = new javax.swing.JCheckBox();
        CBc3 = new javax.swing.JCheckBox();
        CBc4 = new javax.swing.JCheckBox();
        CBc5 = new javax.swing.JCheckBox();
        CBd1 = new javax.swing.JCheckBox();
        CBd2 = new javax.swing.JCheckBox();
        CBd3 = new javax.swing.JCheckBox();
        CBd4 = new javax.swing.JCheckBox();
        CBd5 = new javax.swing.JCheckBox();
        CBe1 = new javax.swing.JCheckBox();
        CBe2 = new javax.swing.JCheckBox();
        CBe3 = new javax.swing.JCheckBox();
        CBe4 = new javax.swing.JCheckBox();
        CBe5 = new javax.swing.JCheckBox();
        btncetakhargatiket = new javax.swing.JButton();
        btncetaktiket = new javax.swing.JButton();
        txtCetakFilm = new javax.swing.JTextField();
        txtCetakWaktuFilm = new javax.swing.JTextField();
        txtCetakJenisTeater = new javax.swing.JTextField();
        txtCetakKursi = new javax.swing.JTextField();
        btnExit = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        txtCetakHargaTiket = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("APLIKASI PEMESANAN TIKET BIOSKOP - E-CASHIER CINEMA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 805, -1));

        jLabel2.setText("PILIH NAMA FILM");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 140, -1));

        cbNamaFilm.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbNamaFilm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Harry Potter and the Sorcerer's Stone", "Harry Potter and the Chamber of Secrets", "Harry Potter and the Prisioner of Azkaban", "Harry Potter and the Goblet of Fire", "Harry Potter and the Order of the Phoenix", "Harry Potter and the Half-Blood Prince", "Harry Potter and the Deahtly Hallows - Part 1", "Harry Potter and the Deahtly Hallows - Part 2" }));
        jPanel1.add(cbNamaFilm, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 270, -1));

        jLabel3.setText("PILIH WAKTU FILM");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 140, -1));

        RBGWaktuFilm.add(RB1);
        RB1.setText("10:00");
        jPanel1.add(RB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, -1));

        RBGWaktuFilm.add(RB2);
        RB2.setText("11:00");
        jPanel1.add(RB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, -1));

        RBGWaktuFilm.add(RB3);
        RB3.setText("13:00");
        jPanel1.add(RB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, -1));

        RBGWaktuFilm.add(RB4);
        RB4.setText("15:00");
        jPanel1.add(RB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, -1, -1));

        RBGWaktuFilm.add(RB5);
        RB5.setText("17:00");
        jPanel1.add(RB5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, -1, -1));

        RBGWaktuFilm.add(RB6);
        RB6.setText("19:30");
        jPanel1.add(RB6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, -1));

        RBGWaktuFilm.add(RB7);
        RB7.setText("20:00");
        jPanel1.add(RB7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, -1, -1));

        RBGWaktuFilm.add(RB8);
        RB8.setText("22:00");
        jPanel1.add(RB8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, -1, -1));

        RBGWaktuFilm.add(RB9);
        RB9.setText("24:00");
        jPanel1.add(RB9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, -1, -1));

        jLabel4.setText("PILIH JENIS TEATER");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 140, -1));

        RBGJenisTeater.add(RBReguler);
        RBReguler.setText("Reguler");
        RBReguler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBRegulerActionPerformed(evt);
            }
        });
        jPanel1.add(RBReguler, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, -1, -1));

        RBGJenisTeater.add(RBPlatinum);
        RBPlatinum.setText("Platinum");
        RBPlatinum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBPlatinumActionPerformed(evt);
            }
        });
        jPanel1.add(RBPlatinum, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, -1, -1));

        RBGJenisTeater.add(RBGold);
        RBGold.setText("Gold");
        RBGold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBGoldActionPerformed(evt);
            }
        });
        jPanel1.add(RBGold, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, -1, -1));

        jLabel5.setText("MASUKKAN JUMLAH TIKET");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 170, -1));

        txtJumlahTiket.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtJumlahTiketKeyTyped(evt);
            }
        });
        jPanel1.add(txtJumlahTiket, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 133, -1));

        btnPilihKursi.setText("PILIH KURSI");
        btnPilihKursi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilihKursiActionPerformed(evt);
            }
        });
        jPanel1.add(btnPilihKursi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 140, -1));

        CBa1.setText("A1");
        jPanel1.add(CBa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, -1, -1));

        CBa2.setText("A2");
        jPanel1.add(CBa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, -1, -1));

        CBa3.setText("A3");
        jPanel1.add(CBa3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, -1, -1));

        CBa4.setText("A4");
        jPanel1.add(CBa4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, -1, -1));

        CBa5.setText("A5");
        jPanel1.add(CBa5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, -1, -1));

        CBb1.setText("B1");
        jPanel1.add(CBb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, -1, -1));

        CBb2.setText("B2");
        jPanel1.add(CBb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, -1, -1));

        CBb3.setText("B3");
        jPanel1.add(CBb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, -1, -1));

        CBb4.setText("B4");
        jPanel1.add(CBb4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, -1, -1));

        CBb5.setText("B5");
        jPanel1.add(CBb5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, -1, -1));

        CBc1.setText("C1");
        jPanel1.add(CBc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, -1, -1));

        CBc2.setText("C2");
        jPanel1.add(CBc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, -1, -1));

        CBc3.setText("C3");
        jPanel1.add(CBc3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, -1, -1));

        CBc4.setText("C4");
        jPanel1.add(CBc4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, -1, -1));

        CBc5.setText("C5");
        jPanel1.add(CBc5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, -1, -1));

        CBd1.setText("D1");
        jPanel1.add(CBd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, -1, -1));

        CBd2.setText("D2");
        jPanel1.add(CBd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, -1, -1));

        CBd3.setText("D3");
        jPanel1.add(CBd3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, -1, -1));

        CBd4.setText("D4");
        jPanel1.add(CBd4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, -1, -1));

        CBd5.setText("D5");
        jPanel1.add(CBd5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, -1, -1));

        CBe1.setText("E1");
        jPanel1.add(CBe1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, -1, -1));

        CBe2.setText("E2");
        jPanel1.add(CBe2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, -1, -1));

        CBe3.setText("E3");
        jPanel1.add(CBe3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, -1, -1));

        CBe4.setText("E4");
        jPanel1.add(CBe4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, -1, -1));

        CBe5.setText("E5");
        jPanel1.add(CBe5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, -1, -1));

        btncetakhargatiket.setText("CETAK HARGA TIKET");
        btncetakhargatiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncetakhargatiketActionPerformed(evt);
            }
        });
        jPanel1.add(btncetakhargatiket, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, -1, -1));

        btncetaktiket.setText("CETAK TIKET");
        btncetaktiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncetaktiketActionPerformed(evt);
            }
        });
        jPanel1.add(btncetaktiket, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, 140, -1));

        txtCetakFilm.setEditable(false);
        jPanel1.add(txtCetakFilm, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 290, -1));

        txtCetakWaktuFilm.setEditable(false);
        jPanel1.add(txtCetakWaktuFilm, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, 290, -1));

        txtCetakJenisTeater.setEditable(false);
        jPanel1.add(txtCetakJenisTeater, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, 290, -1));

        txtCetakKursi.setEditable(false);
        jPanel1.add(txtCetakKursi, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, 290, -1));

        btnExit.setText("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 400, 60, -1));

        btnreset.setText("CETAK LAGI");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });
        jPanel1.add(btnreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 400, -1, -1));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Harga \nReguler = Rp.25.000\nPlatinum = Rp. 30.000\nGold = Rp.50.000");
        jScrollPane2.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 310, 70));

        txtCetakHargaTiket.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCetakHargaTiket.setText("Harga");
        jPanel1.add(txtCetakHargaTiket, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 310, 20));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 450, 40));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 30, 320));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 450, 40));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 450, 40));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 450, 40));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 450, 40));

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(0, 51, 51));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea2.setRows(5);
        jTextArea2.setText("\t          Tiket Anda");
        jScrollPane1.setViewportView(jTextArea2);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 310, 170));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 819, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(835, 469));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btncetakhargatiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncetakhargatiketActionPerformed
        // TODO add your handling code here:
        //cetak harga tiket
        Integer jumlah = Integer.parseInt(txtJumlahTiket.getText());
        int total = harga * jumlah;
        txtCetakHargaTiket.setText(""+total);
    }//GEN-LAST:event_btncetakhargatiketActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btncetaktiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncetaktiketActionPerformed
        // TODO add your handling code here:
        //cetak nama film
        String text;
        text = (String)cbNamaFilm.getSelectedItem();
        txtCetakFilm.setText(text);
        //batas akhir cetak nama film
        
        //cetak waktu film
        String WaktuFilm;
        WaktuFilm = "";
        if(RB1.isSelected()) {
            WaktuFilm += RB1.getText() + " ";
        }
        if(RB2.isSelected()) {
            WaktuFilm += RB2.getText() + " ";
        }
        if(RB3.isSelected()) {
            WaktuFilm += RB3.getText() + " ";
        }
        if(RB4.isSelected()) {
            WaktuFilm += RB4.getText() + " ";
        }
        if(RB5.isSelected()) {
            WaktuFilm += RB5.getText() + " ";
        }
        if(RB6.isSelected()) {
            WaktuFilm += RB6.getText() + " ";
        }
        if(RB7.isSelected()) {
            WaktuFilm += RB7.getText() + " ";
        }
        if(RB8.isSelected()) {
            WaktuFilm += RB8.getText() + " ";
        }
        if(RB9.isSelected()) {
            WaktuFilm += RB9.getText() + " ";
        }
        if (WaktuFilm.equals("")) {
            txtCetakWaktuFilm.setText("Anda Belum Memilih Waktu Film");
        } else {
            WaktuFilm = WaktuFilm.substring(0,WaktuFilm.length()-1) + ".";
            txtCetakWaktuFilm.setText("Waktu Menonton Anda Jam " + WaktuFilm);
        }
        //batas akhir cetak waktu film
        
        //cetak jenis teater
        String JenisTeater;
        JenisTeater = "";
        if(RBReguler.isSelected()) {
            JenisTeater += RBReguler.getText() + " ";
        }
        if(RBPlatinum.isSelected()) {
            JenisTeater += RBPlatinum.getText() + " ";
        }  
        if(RBGold.isSelected()) {
            JenisTeater += RBGold.getText() + " ";
        }
        if (JenisTeater.equals("")) {
            txtCetakJenisTeater.setText("Anda Belum Memilih Teater");
        } else {
            JenisTeater = JenisTeater.substring(0,JenisTeater.length()-1) + ".";
            txtCetakJenisTeater.setText("Anda Memilih Teater " + JenisTeater);
        }
        //batas akhir cetak jenis teater
       
        //cetak kursi
        String Kursi;
        Kursi = "";
        if (CBa1.isSelected()){
            Kursi += CBa1.getText() + " ";
        }
        if (CBa2.isSelected()){
            Kursi += CBa2.getText() + " ";
        }
        if (CBa3.isSelected()){
            Kursi += CBa3.getText() + " ";
        }
        if (CBa4.isSelected()){
            Kursi += CBa4.getText() + " ";
        }
        if (CBa5.isSelected()){
            Kursi += CBa5.getText() + " ";
        }
        if (CBb1.isSelected()){
            Kursi += CBb1.getText() + " ";
        }
        if (CBb2.isSelected()){
            Kursi += CBb2.getText() + " ";
        }
        if (CBb3.isSelected()){
            Kursi += CBb3.getText() + " ";
        }
        if (CBb4.isSelected()){
            Kursi += CBb4.getText() + " ";
        }
        if (CBb5.isSelected()){
            Kursi += CBb5.getText() + " ";
        }
        if (CBc1.isSelected()){
            Kursi += CBc1.getText() + " ";
        }
        if (CBc2.isSelected()){
            Kursi += CBc2.getText() + " ";
        }
        if (CBc3.isSelected()){
            Kursi += CBc3.getText() + " ";
        }
        if (CBc4.isSelected()){
            Kursi += CBc4.getText() + " ";
        }
        if (CBc5.isSelected()){
            Kursi += CBc5.getText() + " ";
        }
        if (CBd1.isSelected()){
            Kursi += CBd1.getText() + " ";
        }
        if (CBd2.isSelected()){
            Kursi += CBd2.getText() + " ";
        }
        if (CBd3.isSelected()){
            Kursi += CBd3.getText() + " ";
        }
        if (CBd4.isSelected()){
            Kursi += CBd4.getText() + " ";
        }
        if (CBd5.isSelected()){
            Kursi += CBd5.getText() + " ";
        }
        if (CBe1.isSelected()){
            Kursi += CBe1.getText() + " ";
        }
        if (CBe2.isSelected()){
            Kursi += CBe2.getText() + " ";
        }
        if (CBe3.isSelected()){
            Kursi += CBe3.getText() + " ";
        }
        if (CBe4.isSelected()){
            Kursi += CBe4.getText() + " ";
        }
        if (CBe5.isSelected()){
            Kursi += CBe5.getText() + " ";
        }
        if (Kursi.equals("")) {
            txtCetakKursi.setText("Anda Belum Memilih Kursi");
        } else {
            Kursi = Kursi.substring(0, Kursi.length()-1) + ".";
            txtCetakKursi.setText("Anda Memilih Kursi " + Kursi);
        }
        //batas akhir dari cetak kursi
    }//GEN-LAST:event_btncetaktiketActionPerformed

    private void RBRegulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBRegulerActionPerformed
        // TODO add your handling code here:
        harga = 25000;
    }//GEN-LAST:event_RBRegulerActionPerformed

    private void RBPlatinumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBPlatinumActionPerformed
        // TODO add your handling code here:
        harga = 30000;
    }//GEN-LAST:event_RBPlatinumActionPerformed

    private void RBGoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBGoldActionPerformed
        // TODO add your handling code here:
        harga = 50000;
    }//GEN-LAST:event_RBGoldActionPerformed

    private void txtJumlahTiketKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJumlahTiketKeyTyped
        // TODO add your handling code here:
        FilterAngka(evt); //memanggil method input hanya angka
    }//GEN-LAST:event_txtJumlahTiketKeyTyped

    private void kursihilang(){ //awal dari membuat method kursi hilang
       CBa1.setVisible(false);
       CBa2.setVisible(false);
       CBa3.setVisible(false);
       CBa4.setVisible(false);
       CBa5.setVisible(false);
       
       CBb1.setVisible(false);
       CBb2.setVisible(false);
       CBb3.setVisible(false);
       CBb4.setVisible(false);
       CBb5.setVisible(false);
       
       CBc1.setVisible(false);
       CBc2.setVisible(false);
       CBc3.setVisible(false);
       CBc4.setVisible(false);
       CBc5.setVisible(false);
       
       CBd1.setVisible(false);
       CBd2.setVisible(false);
       CBd3.setVisible(false);
       CBd4.setVisible(false);
       CBd5.setVisible(false);
       
       CBe1.setVisible(false);
       CBe2.setVisible(false);
       CBe3.setVisible(false);
       CBe4.setVisible(false);
       CBe5.setVisible(false);
    }//akhir dari method membuat kursi hilang
    
    private void kursimuncul(){ //awal dari method membuat kursi muncul
       CBa1.setVisible(true);
       CBa2.setVisible(true);
       CBa3.setVisible(true);
       CBa4.setVisible(true);
       CBa5.setVisible(true);
       
       CBb1.setVisible(true);
       CBb2.setVisible(true);
       CBb3.setVisible(true);
       CBb4.setVisible(true);
       CBb5.setVisible(true);
       
       CBc1.setVisible(true);
       CBc2.setVisible(true);
       CBc3.setVisible(true);
       CBc4.setVisible(true);
       CBc5.setVisible(true);
       
       CBd1.setVisible(true);
       CBd2.setVisible(true);
       CBd3.setVisible(true);
       CBd4.setVisible(true);
       CBd5.setVisible(true);
       
       CBe1.setVisible(true);
       CBe2.setVisible(true);
       CBe3.setVisible(true);
       CBe4.setVisible(true);
       CBe5.setVisible(true);
    }//akhir dari method membuat kursi muncul
    
    private void btnPilihKursiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilihKursiActionPerformed
        // TODO add your handling code here:
        kursimuncul();
    }//GEN-LAST:event_btnPilihKursiActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // TODO add your handling code here:
        txtCetakFilm.setText("");
        txtCetakHargaTiket.setText("");
        txtCetakJenisTeater.setText("");
        txtCetakKursi.setText("");
        txtCetakWaktuFilm.setText("");
        txtJumlahTiket.setText("");
        RBGWaktuFilm.clearSelection();
        RBGJenisTeater.clearSelection();
        CBa1.setSelected(false);
        CBa2.setSelected(false);
        CBa3.setSelected(false);
        CBa4.setSelected(false);
        CBa5.setSelected(false);
        CBb1.setSelected(false);
        CBb2.setSelected(false);
        CBb3.setSelected(false);
        CBb4.setSelected(false);
        CBb5.setSelected(false);
        CBc1.setSelected(false);
        CBc2.setSelected(false);
        CBc3.setSelected(false);
        CBc4.setSelected(false);
        CBc5.setSelected(false);
        CBd1.setSelected(false);
        CBd2.setSelected(false);
        CBd3.setSelected(false);
        CBd4.setSelected(false);
        CBd5.setSelected(false);
        CBe1.setSelected(false);
        CBe2.setSelected(false);
        CBe3.setSelected(false);
        CBe4.setSelected(false);
        CBe5.setSelected(false);
    }//GEN-LAST:event_btnresetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BioskopQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BioskopQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BioskopQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BioskopQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BioskopQ().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CBa1;
    private javax.swing.JCheckBox CBa2;
    private javax.swing.JCheckBox CBa3;
    private javax.swing.JCheckBox CBa4;
    private javax.swing.JCheckBox CBa5;
    private javax.swing.JCheckBox CBb1;
    private javax.swing.JCheckBox CBb2;
    private javax.swing.JCheckBox CBb3;
    private javax.swing.JCheckBox CBb4;
    private javax.swing.JCheckBox CBb5;
    private javax.swing.JCheckBox CBc1;
    private javax.swing.JCheckBox CBc2;
    private javax.swing.JCheckBox CBc3;
    private javax.swing.JCheckBox CBc4;
    private javax.swing.JCheckBox CBc5;
    private javax.swing.JCheckBox CBd1;
    private javax.swing.JCheckBox CBd2;
    private javax.swing.JCheckBox CBd3;
    private javax.swing.JCheckBox CBd4;
    private javax.swing.JCheckBox CBd5;
    private javax.swing.JCheckBox CBe1;
    private javax.swing.JCheckBox CBe2;
    private javax.swing.JCheckBox CBe3;
    private javax.swing.JCheckBox CBe4;
    private javax.swing.JCheckBox CBe5;
    private javax.swing.JRadioButton RB1;
    private javax.swing.JRadioButton RB2;
    private javax.swing.JRadioButton RB3;
    private javax.swing.JRadioButton RB4;
    private javax.swing.JRadioButton RB5;
    private javax.swing.JRadioButton RB6;
    private javax.swing.JRadioButton RB7;
    private javax.swing.JRadioButton RB8;
    private javax.swing.JRadioButton RB9;
    private javax.swing.ButtonGroup RBGJenisTeater;
    private javax.swing.ButtonGroup RBGWaktuFilm;
    private javax.swing.JRadioButton RBGold;
    private javax.swing.JRadioButton RBPlatinum;
    private javax.swing.JRadioButton RBReguler;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnPilihKursi;
    private javax.swing.JButton btncetakhargatiket;
    private javax.swing.JButton btncetaktiket;
    private javax.swing.JButton btnreset;
    private javax.swing.JComboBox<String> cbNamaFilm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField txtCetakFilm;
    private javax.swing.JLabel txtCetakHargaTiket;
    private javax.swing.JTextField txtCetakJenisTeater;
    private javax.swing.JTextField txtCetakKursi;
    private javax.swing.JTextField txtCetakWaktuFilm;
    private javax.swing.JTextField txtJumlahTiket;
    // End of variables declaration//GEN-END:variables
}
